### ISSUE TITLE
How to tackle optional hasOne/belongsTo (so called 1-0..1) relationship?

### ISSUE THREAD

**Issue by CristianSitov** [tkeer/flattable#2]
I won't get to deep into the subject but it happens sometimes to have one nullable column that references another table.
I see no means to setup this kind of relationship in a flattable. Is there a way though?

**Comment by tkeer** [comment]
Hello @CristianSitov 

I am not entirely sure what you are asking, but if you peek to the tests, and see relationship of `publishers` with `countries`, the `publishers` table has `country_id` column which can be null, and the related entries of country in the publishers' flat table will be empty. 
So it allows you nullable hasOne/BelongsTo relations.

Not sure if it answer your question :), if it doesn't do you mind giving some examples.

**Comment by CristianSitov** [comment]
Oh, that was clumsy from me! 
I'll take a look and get back to you with feedback.

P.S.: Also, me & my team would really like to give a helping hand with this package. I think it can be very useful for one of our projects.

**Comment by tkeer** [comment]
That would be great, you and your team are always welcome!
