### ISSUE TITLE
Issue with callback

### ISSUE THREAD

**Issue by jonathanmaloy** [tkeer/flattable#4]
I was trying to use the callback to get some of the columns. I removed a lot of the other columns here for readability. Despite the function returning an array, I receive this error when running the fill command:

`[2021-10-06 22:24:29] local.ERROR: array_values() expects parameter 1 to be array, object given {"exception":"[object] (ErrorException(code: 0): array_values() expects parameter 1 to be array, object given at /www/vendor/tkeer/flattable/src/Builders/ChangesBuilderHelper.php:129)`

It seems I implemented it correctly per the documentation. Did I miss something?

```
public function flattableConfig() {
    return [
        [
            'columns' => [
                'organization_asset_id' => 'id',
            ],
            'type' => 'primary',
            'wheres' => [
                'organization_asset_id' => 'id',
            ],
            'flattable' => 'flat_organization_assets',
            'changes' => [
                'supplier_id' => [
                    'columns' => function (Supplier $supplier): array
                    {
                        return [
                            'supplier_id' => $supplier->exists ? $supplier->id : null,
                            'supplier_country_name' => $supplier->organization->headquarters->exists
                                ? $supplier->organization->headquarters->country->name : null,
                            'supplier_country_code' => $supplier->organization->headquarters->exists
                                ? $supplier->organization->headquarters->country->iso3 : null
                        ];
                    },
                    'wheres' => [
                        'id' => 'supplier_id'
                    ],
                    'table' => 'suppliers'
                ]
            ]
        ]
    ];
}

**Comment by tkeer** [comment]
It doesn't support the callback for sub tables ('changes'). 
Also, values for `changes` array expects column names of the table instead of the actual data. 
https://github.com/tkeer/flattable/#3-country-of-the-publisher-in-books-flattable

Supporting callback for `changes` columns doesn't seem hard, I will add it.

**Comment by jonathanmaloy** [comment]
Thank you!
